### ISSUE TITLE
Feedback for rustic_core (DX)

### ISSUE THREAD

**Issue by simonsan** [talss89/sprout#3]
Hey there,
as you are an early user of rustic_core, we would like to understand better how the API of rustic_core fares you. Do you have any feedback, do you miss anything? :-)

**Comment by talss89** [comment]
Hey @simonsan, thanks for getting in touch! I think I must have started this project hours (if not minutes) after `rustic_core` 0.2.0 was released. Serendipity, eh?

Quick caveat - I'm very new to Rust.

The TLDR is that I'm really impressed. The `***Options` pattern is very friendly and intuitive, and the baked in Serializable traits are an excellent decision.

I found implementing progress bars with `indicatif` and implementing `ProgressBars` quite straightforward, although it would be great if a method was available on `Repository` programatically disable / enable progress bars after the instance was created. Something like `repo.progress_hidden(true)`.

I'm continuing to work on sprout, so I'll feed back any further DX ideas or issues to the main repo.
